server:
  port: ${SERVER:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coursesDb
    username: joserivera
    password: Md55015501
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


eureka:
  fetch-registry: true
  register-with-eureka: true
  instance:
    hostname:
      instance-id: "${spring.application.name}:${spring.application.instance-id:${random.value}}"
