server:
  port: 8003

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gradesDb
    username: joserivera
    password: Md55015501
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect