server:
  port: 8081
spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jriverah46/InstitutionSystem
          username: "jriverah46"
          password: "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"
          search-paths: config-data



