server:
  port: 8081
spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jriverah46/InstitutionSystem
          username: jriverah46
          password: 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
          search-paths: config-data



